Repository DIT112-V20/group-06, pull requests merged in 2020-04, with the labels that each got.

#13 Create basic obstacle avoidance sketch
  src/car/avoid/avoid.ino
Labels: sprint1

#17 Dance moves
  src/car/avoid/avoid.ino
  src/carLogic/carLogic.ino
Labels: sprint1

#26 Bug fixing #1
  src/carLogic/carLogic.ino
Labels: sprint2

#35 App skeleton
  src/app/.gitignore
  src/app/.idea/codeStyles/codeStyleConfig.xml
  src/app/UI/UI prototype #1.pdf
  src/app/app/.gitignore
  src/app/app/build.gradle
  src/app/app/proguard-rules.pro
  src/app/app/src/androidTest/java/com/example/djsmartcar/ExampleInstrumentedTest.kt
  src/app/app/src/main/AndroidManifest.xml
  src/app/app/src/main/java/com/example/djsmartcar/MainActivity.kt
  src/app/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  src/app/app/src/main/res/drawable/ic_launcher_background.xml
  src/app/app/src/main/res/layout/activity_main.xml
  src/app/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  src/app/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  src/app/app/src/main/res/mipmap-hdpi/ic_launcher.png
  src/app/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  src/app/app/src/main/res/mipmap-mdpi/ic_launcher.png
  src/app/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  src/app/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  src/app/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  src/app/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  src/app/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  src/app/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  src/app/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  src/app/app/src/main/res/values/colors.xml
  src/app/app/src/main/res/values/strings.xml
  src/app/app/src/main/res/values/styles.xml
  src/app/app/src/test/java/com/example/djsmartcar/ExampleUnitTest.kt
  src/app/build.gradle
  src/app/gradle.properties
  src/app/gradle/wrapper/gradle-wrapper.jar
  src/app/gradle/wrapper/gradle-wrapper.properties
  src/app/gradlew
  src/app/gradlew.bat
  src/app/settings.gradle
Labels: app, sprint3

#38 Fourth dance move
  src/carLogic/carLogic.ino
Labels: sprint3, user story
